name: PhantomImitationEnchantment
version: '1.0-SNAPSHOT'
main: info.infinf.phantomImitationEnchantment.PhantomImitationEnchantment
api-version: '1.21'
bootstrapper: info.infinf.phantomImitationEnchantment.BootStrap
